// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Price struct {
	AptName string
	LawdCd  string
	Month   string
	AreaInt int64
	Area    float64
	Median  int64
	Count   int64
}
