// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const getCachedMonths = `-- name: GetCachedMonths :many
SELECT month
FROM prices
WHERE apt_name = ? AND lawd_cd = ? AND area_int = ?
`

type GetCachedMonthsParams struct {
	AptName string
	LawdCd  string
	AreaInt int64
}

func (q *Queries) GetCachedMonths(ctx context.Context, arg GetCachedMonthsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCachedMonths, arg.AptName, arg.LawdCd, arg.AreaInt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var month string
		if err := rows.Scan(&month); err != nil {
			return nil, err
		}
		items = append(items, month)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPriceIgnore = `-- name: InsertPriceIgnore :exec
INSERT OR IGNORE INTO prices (apt_name, lawd_cd, month, area_int, area, median, count)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPriceIgnoreParams struct {
	AptName string
	LawdCd  string
	Month   string
	AreaInt int64
	Area    float64
	Median  int64
	Count   int64
}

func (q *Queries) InsertPriceIgnore(ctx context.Context, arg InsertPriceIgnoreParams) error {
	_, err := q.db.ExecContext(ctx, insertPriceIgnore,
		arg.AptName,
		arg.LawdCd,
		arg.Month,
		arg.AreaInt,
		arg.Area,
		arg.Median,
		arg.Count,
	)
	return err
}

const listPricesByApt = `-- name: ListPricesByApt :many
SELECT month, area_int, area, median, count
FROM prices
WHERE apt_name = ? AND lawd_cd = ? AND area_int = ?
ORDER BY month DESC
`

type ListPricesByAptParams struct {
	AptName string
	LawdCd  string
	AreaInt int64
}

type ListPricesByAptRow struct {
	Month   string
	AreaInt int64
	Area    float64
	Median  int64
	Count   int64
}

func (q *Queries) ListPricesByApt(ctx context.Context, arg ListPricesByAptParams) ([]ListPricesByAptRow, error) {
	rows, err := q.db.QueryContext(ctx, listPricesByApt, arg.AptName, arg.LawdCd, arg.AreaInt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPricesByAptRow
	for rows.Next() {
		var i ListPricesByAptRow
		if err := rows.Scan(
			&i.Month,
			&i.AreaInt,
			&i.Area,
			&i.Median,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPrice = `-- name: UpsertPrice :exec
INSERT OR REPLACE INTO prices (apt_name, lawd_cd, month, area_int, area, median, count)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type UpsertPriceParams struct {
	AptName string
	LawdCd  string
	Month   string
	AreaInt int64
	Area    float64
	Median  int64
	Count   int64
}

func (q *Queries) UpsertPrice(ctx context.Context, arg UpsertPriceParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrice,
		arg.AptName,
		arg.LawdCd,
		arg.Month,
		arg.AreaInt,
		arg.Area,
		arg.Median,
		arg.Count,
	)
	return err
}
